DELIMITER $$

DROP PROCEDURE IF EXISTS HOTEL.CTRLPS_RESERVATION_LIST$$

CREATE DEFINER=`root`@`localhost`

PROCEDURE `CTRLPS_RESERVATION_LIST`( IN idHotel INT,
									 IN param VARCHAR(255) )

BEGIN
	SELECT  RES.MAINP_ID_HOTEL				ID_HOTEL,
			RES.RESVP_ID_RESERVATION		ID_RESERVATION,
			RES.RESVC_RESERVATION_TYPE		RESERVATION_TYPE,
			DATE_FORMAT(RES.RESVC_ARRIVAL,'%d/%m/%Y')
											ARRIVAL,
			DATE_FORMAT(RES.RESVC_DEPARTURE,'%d/%m/%Y')
											DEPARTURE,
			RES.RESVC_NIGHTS 				NIGHTS,
			RES.RESVC_ADULTS 				ADULTS,
			RES.RESVC_CHILDREN 				CHILDREN,
			RES.RTYPF_ID_ROOMTYPE 			ID_ROOMTYPE,
			RTP.RTYPC_ROOMTYPE_CODE			ROOMTYPE_CODE,
			RTP.RTYPC_DESCRIPTION			ROOMTYPE_DESCRIPTION,
			RES.RESVC_QUANTITY 				QUANTITY,
			RES.ROOMF_ID_ROOM		 		ID_ROOM,
			RES.RESVC_VIP_CODE 				VIP_CODE,
			RES.SRCEF_ID_SOURCE				ID_SOURCE,
			RES.RESVC_ROOM_RATE 			ROOM_RATE,
			RES.RESVC_TOTAL_ROOM 			TOTAL_ROOM, /* Total a pagar x alojamiento */
			case when DATE_FORMAT(RES.RESVC_PAYMENT_DUE,'%d/%m/%Y') = 0 then '' else RES.RESVC_PAYMENT_DUE end
											PAYMENT_DUE,
			RES.RESVF_PAYMENT_TYPE			PAYMENT_TYPE,
			RES.RESVC_VOUCHER				VOUCHER,
			RES.RESVC_HOTEL_INSTRUCTIONS	HOTEL_INSTRUCTIONS,
			RES.RESVC_GUEST_INSTRUCTIONS	GUEST_INSTRUCTIONS,
			RES.RESVC_MADE_BY				MADE_BY,
			DATE_FORMAT(RES.RESVC_MADE_ON,'%d/%m/%Y')
											MADE_ON,
			RES.RESVC_UPDATED_BY 			UPDATED_BY,
			DATE_FORMAT(RES.RESVC_LAST_UPDATE,'%d/%m/%Y')
											LAST_UPDATE,
			RES.RESVC_STATUS				STATUS
       FROM CTRLT_RESERVATION RES
            LEFT JOIN CTRLT_ROOMTYPE RTP
                   ON RES.RTYPF_ID_ROOMTYPE = RTP.RTYPP_ID_ROOMTYPE
			/*LEFT JOIN CTRLT_GUEST  GST
				   ON RES.MAINP_ID_HOTEL = GST.NIDHOTEL
				  AND RES.RESVP_ID_RESERVATION = RGS.NIDRESERVATION*/
			/*LEFT JOIN CTRLT_CUSTOMER CUS
				   ON GST.NIDHOTEL = CUS.NHOTELREGISTRATION
				  AND GST.NIDCUSTOMER = CUS.NIDCUSTOMER*/
	 WHERE RES.MAINP_ID_HOTEL = p_id_hotel
	   -- AND CUS.TLASTNAME1 LIKE CONCAT(PARAM,'%')
	 ORDER BY RES.RESVP_ID_RESERVATION;

END$$

DELIMITER ;