DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_TABLE_ITEM_LIST`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `CTRLPS_TABLE_ITEM_LIST`(
					IN p_id_module VARCHAR(02),
					IN p_id_table  VARCHAR(02),
					IN p_status	   VARCHAR(01) )
BEGIN
	SELECT 	-- ITMTP_ID_TABLE			ID_TABLE,
			ITMTP_ID_ITEM			ID_ITEM,
			ITMTP_ITEM_DESCRIPTION	ITEM_DESCRIPTION,
			ITMTP__STATUS			STATUS
	  FROM CTRLT_TABLE_ITEM
	 WHERE ITMTP_ID_TABLE = p_id_table
	   AND ( p_status = ''  OR ITMTP__STATUS = p_status );
END$$

DELIMITER ;