DELIMITER $$

DROP PROCEDURE IF EXISTS HOTEL.CTRLPS_FLASH_STATUS$$

CREATE DEFINER=`root`@`localhost`

PROCEDURE HOTEL.CTRLPS_FLASH_STATUS( IN p_id_hotel 		varchar(02),
									 IN p_id_roomtype 	varchar(02),
									 IN p_status_date 	varchar(10) )
BEGIN
	DECLARE BLANK VARCHAR(01) DEFAULT '';

	SELECT	RTS.MAINP_ID_HOTEL			AS ID_HOTEL,
			RTS.RTSTP_ID_ROOMTYPE		AS ID_ROOMTYPE,
			DATE_FORMAT(RTS.RTSTP_STATUS_DAY, '%d/%m/%Y')
										AS STATUS_DAY,
			RTP.RTYPC_AVAILABLE_ROOMS	AS TOTAL_ROOMS,
			RTS.RTSTC_AVAILABLE_ROOMS	AS AVAILABLE_ROOMS,
			RTS.RTSTC_TENTATIVE_ROOMS	AS TENTATIVE_ROOMS,
			RTS.RTSTC_COMFIRMED_ROOMS	AS COMFIRMED_ROOMS,
			RTS.RTSTC_LOCKED_ROOMS		AS LOCKED_ROOMS,
			RTS.RTSTC_MAINTENANCE_ROOMS	AS MAINTENANCE_ROOMS,
			RTS.RTSTC_RESERVATION_TYPE	AS RESERVATION_TYPE,
			RTS.RTSTC_LAST_UPDATE		AS LAST_UPDATE
	  FROM CTRLT_ROOMTYPE_STATUS RTS,
		   CTRLT_ROOMTYPE RTP
	 WHERE p_id_hotel = RTS.MAINP_ID_HOTEL
	   AND ( p_id_roomtype = BLANK
			OR p_id_roomtype = RTS.RTSTP_ID_ROOMTYPE )
	   AND ( p_status_date = BLANK
			OR p_status_date <= RTS.RTSTP_STATUS_DAY )
       AND ( RTS.MAINP_ID_HOTEL = RTP.MAINP_ID_HOTEL
			AND RTS.RTSTP_ID_ROOMTYPE = RTP.RTYPP_ID_ROOMTYPE );

END$$

DELIMITER ;