DELIMITER $$

DROP PROCEDURE IF EXISTS HOTEL.CTRLPS_ROOMTYPE_STATUS_LIST$$

CREATE DEFINER=`root`@`localhost` PROCEDURE CTRLPS_ROOMTYPE_STATUS_LIST(
					    IN p_id_hotel			varchar(02),
						IN p_id_roomtype		varchar(02),
						IN p_start_status_date	varchar(10),
						IN p_end_status_date	varchar(10) )

BEGIN
	DECLARE BLANK varchar(01) DEFAULT '';
	DECLARE v_id_roomtype varchar(01) DEFAULT IFNULL(p_id_roomtype, '');

	SELECT MAINP_ID_HOTEL			ID_HOTEL,
			RTSTP_ID_ROOMTYPE 		ID_ROOMTYPE,
			RTSTP_STATUS_DAY		STATUS_DAY,
			RTSTC_TOTAL_ROOMS		TOTAL_ROOMS,
			RTSTC_AVAILABLE_ROOMS	AVAILABLE_ROOMS,
			RTSTC_TENTATIVE_ROOMS	TENTATIVE_ROOMS,
			RTSTC_COMFIRMED_ROOMS	COMFIRMED_ROOMS,
			RTSTC_LOCKED_ROOMS		LOCKED_ROOMS,
			RTSTC_MAINTENANCE_ROOMS	MAINTENANCE_ROOMS,
			RTSTC_RESERVATION_TYPE	RESERVATION_TYPE,
			RTSTC_TOTAL_CHILDREN	TOTAL_CHILDREN,
			RTSTC_TOTAL_ADULTS		TOTAL_ADULTS,
			RTSTC_LAST_UPDATE		LAST_UPDATE
      FROM CTRLT_ROOMTYPE_STATUS
     WHERE MAINP_ID_HOTEL = p_id_hotel
	   AND ( v_id_roomtype = BLANK OR RTSTP_ID_ROOMTYPE = p_id_roomtype );

END$$

DELIMITER ;