DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_GUEST`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `CTRLPS_GUEST`(
							IN p_id_hotel varchar(02),
							IN p_id_reservation varchar(06),
							IN p_status  varchar(01) )
BEGIN
		SELECT 	MAINP_ID_HOTEL			ID_HOTEL,
				RESVP_ID_RESERVATION	ID_RESERVATION,
				g.CUSTP_ID_CUSTOMER		ID_CUSTOMER,
				c.CUSTC_DOCUMENT_NUMBER	DOCUMENT_NUMBER,
				CONCAT(c.CUSTC_LASTNAME1, ', ', c.CUSTC_FIRSTNAME)
										CUSTOMER_NAMES,
				GUESC_STATUS			STATUS
		  FROM CTRLT_GUEST g
				LEFT JOIN CTRLT_CUSTOMER c ON g.CUSTP_ID_CUSTOMER = c.CUSTP_ID_CUSTOMER
		 WHERE p_id_hotel = MAINP_ID_HOTEL
		   AND p_id_reservation = RESVP_ID_RESERVATION;
END$$

DELIMITER ;