DELIMITER $$

DROP PROCEDURE IF EXISTS HOTEL.CTRLPS_ROOMTYPE_LIST$$

CREATE /*DEFINER=`root`@`localhost`*/

PROCEDURE `CTRLPS_ROOMTYPE_LIST`(IN p_id_hotel varchar(02),
								 IN p_status   varchar(01) )
BEGIN

	SELECT MAINP_ID_HOTEL		 ID_HOTEL,
	       RTYPP_ID_ROOMTYPE	 ID_ROOMTYPE,
	       RTYPC_ROOMTYPE_CODE	 ROOMTYPE_CODE,
		   RTYPC_DESCRIPTION	 DESCRIPTION,
		   RTYPC_RACK_RATE		 RACK_RATE,
		   RTYPC_QUANTITY_ROOMS	 QUANTITY_ROOMS,
		   RTYPC_AVAILABLE_ROOMS AVAILABLE_ROOMS,
		   RTYPC_LOCKED_ROOMS	 LOCKED_ROOMS,
		   RTYPC_STATUS 		 STATUS,
		   RTYPC_MADE_BY		 MADE_BY,
		   RTYPC_MADE_ON		 MADE_ON,
		   RTYPC_UPDATED_BY		 UPDATED_BY,
		   RTYPC_LAST_UPDATE	 LAST_UPDATE
	  FROM CTRLT_ROOMTYPE rt
	 WHERE p_id_hotel = MAINP_ID_HOTEL
	   AND ( p_status = '' OR RTYPC_STATUS = p_status );

END$$

DELIMITER ;