DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPD_COUNTRY`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `CTRLPD_COUNTRY`(
								 IN p_id_country int )
BEGIN
	DELETE FROM CTRLT_COUNTRY
	 WHERE CTRYP_ID_COUNTRY = p_id_country;
END$$

DELIMITER ;