DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_RESERVATION`$$

CREATE DEFINER=`root`@`localhost`

PROCEDURE `CTRLPS_RESERVATION`( IN p_id_hotel varchar(01),
								IN p_id_reservation varchar(06) )
BEGIN
	SELECT  MAINP_ID_HOTEL				ID_HOTEL,
			RESVP_ID_RESERVATION		ID_RESERVATION,
			RESVC_RESERVATION_TYPE		RESERVATION_TYPE,
			DATE_FORMAT(RESVC_ARRIVAL,'%d/%m/%Y')
										ARRIVAL,
			DATE_FORMAT(RESVC_DEPARTURE,'%d/%m/%Y')
										DEPARTURE,
			RESVC_NIGHTS 				NIGHTS,
			RESVC_ADULTS 				ADULTS,
			RESVC_CHILDREN 				CHILDREN,
			RTYPF_ID_ROOMTYPE 			ID_ROOMTYPE,
			RESVC_QUANTITY 				QUANTITY,
			ROOMF_ID_ROOM		 		ID_ROOM,
			RESVC_VIP_CODE 				VIP_CODE,
			SRCEF_ID_SOURCE				ID_SOURCE,
			RESVC_ROOM_RATE 			ROOM_RATE,
			RESVC_TOTAL_ROOM 			TOTAL_ROOM, /* Total a pagar x alojamiento */
			case when DATE_FORMAT(RESVC_PAYMENT_DUE,'%d/%m/%Y') = 0 then '' else RESVC_PAYMENT_DUE end
										PAYMENT_DUE,
			RESVF_PAYMENT_TYPE			PAYMENT_TYPE,
			RESVC_VOUCHER				VOUCHER,
			RESVC_HOTEL_INSTRUCTIONS	HOTEL_INSTRUCTIONS,
			RESVC_GUEST_INSTRUCTIONS	GUEST_INSTRUCTIONS,
			RESVC_MADE_BY				MADE_BY,
			DATE_FORMAT(RESVC_MADE_ON,'%d/%m/%Y')
										MADE_ON,
			RESVC_UPDATED_BY 			UPDATED_BY,
			DATE_FORMAT(RESVC_LAST_UPDATE,'%d/%m/%Y')
										LAST_UPDATE,
			RESVC_STATUS				STATUS
	  FROM CTRLT_RESERVATION
	 WHERE MAINP_ID_HOTEL = p_id_hotel
	   AND RESVP_ID_RESERVATION = p_id_reservation;
    END$$

DELIMITER ;