DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_COUNTRY_LIST`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `CTRLPS_COUNTRY_LIST`(
					IN p_pattern varchar(02) )
BEGIN
	SELECT	CTRYP_ID_COUNTRY	ID_COUNTRY,
			CTRYC_COUNTRY_NAME	COUNTRY_NAME,
			CTRYC_ABBREVIATION	ABBREVIATION,
			CTRYC_NATIONALITY	NATIONALITY
	  FROM CTRLT_COUNTRY;
END$$

DELIMITER ;