DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_RATE`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `CTRLPS_RATE`(
								IN p_id_hotel	varchar(02),
								IN p_id_rate	varchar(04),
								IN p_status		varchar(01) )
BEGIN
	SELECT	MAINP_ID_HOTEL			ID_HOTEL,
			RTYPF_ID_ROOM_TYPE		ID_ROOM_TYPE,
			PERIF_ID_PERIOD			ID_PERIOD,
			RATEP_ID_SPECIAL_RATE	ID_SPECIAL_RATE,
			RATEC_VALUE				VALUE,
			RATEC_MADE_BY			MADE_BY,
			RATEC_MADE_ON			MADE_ON,
			RATEC_UPDATED_BY 		UPDATED_BY,
			RATEC_LAST_UPDATE 		LAST_UPDATE,
			RATEC_STATUS 			STATUS
	  FROM CTRLT_RATE
	 WHERE p_id_hotel = MAINP_ID_HOTEL
	   AND p_id_rate  = RATEP_ID_SPECIAL_RATE
	   AND ( p_status = '' OR p_status = RATEC_STATUS );
END$$

DELIMITER ;