DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_ROOMTYPE`$$

CREATE DEFINER=`root`@`localhost`

PROCEDURE `CTRLPS_ROOMTYPE`(IN p_id_hotel		varchar(02),
							IN p_id_roomType	varchar(02),
							IN p_status			varchar(01) )
BEGIN

	SELECT MAINP_ID_HOTEL		 ID_HOTEL,
	       RTYPP_ID_ROOMTYPE	 ID_ROOMTYPE,
	       RTYPC_ROOMTYPE_CODE	 ROOMTYPE_CODE,
		   RTYPC_DESCRIPTION	 DESCRIPTION,
		   RTYPC_RACK_RATE		 RACK_RATE,
		   RTYPC_QUANTITY_ROOMS	 QUANTITY_ROOMS,
		   RTYPC_AVAILABLE_ROOMS AVAILABLE_ROOMS,
		   RTYPC_LOCKED_ROOMS	 LOCKED_ROOMS,
		   RTYPC_STATUS 		 STATUS,
		   RTYPC_MADE_BY		 MADE_BY,
		   RTYPC_MADE_ON		 MADE_ON,
		   RTYPC_UPDATED_BY		 UPDATED_BY,
		   RTYPC_LAST_UPDATE	 LAST_UPDATE
	  FROM HOTEL.CTRLT_ROOMTYPE
	 WHERE p_id_hotel = MAINP_ID_HOTEL
	   AND p_id_roomtype = RTYPP_ID_ROOMTYPE
	   AND ( p_status = '' OR p_status = RTYPC_STATUS );

END$$

DELIMITER ;