DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_COUNTRY`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `CTRLPS_COUNTRY`(
								IN p_id_country int )
BEGIN
	SELECT	CTRYP_ID_COUNTRY	ID_COUNTRY,
			CTRYC_COUNTRY_NAME	COUNTRY_NAME,
			CTRYC_ABBREVIATION	ABBREVIATION,
			CTRYC_NATIONALITY	NATIONALITY
	  FROM CTRLT_COUNTRY
	 WHERE p_id_country = CTRYP_ID_COUNTRY;
END$$

DELIMITER ;