DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_SOURCE_TYPE_LIST`$$

CREATE DEFINER=`root`@`localhost`

PROCEDURE `CTRLPS_SOURCE_TYPE_LIST`(IN p_description varchar(20),
									IN p_status		 varchar(01) )
BEGIN
	DECLARE BLANK varchar(01) DEFAULT '';

	DECLARE v_description varchar(20) DEFAULT ifnull(concat(p_description,'%'),'%');
	DECLARE v_status varchar(01) DEFAULT ifnull(p_status, BLANK);

	SELECT	SRCTP_ID_SOURCE_TYPE	ID_SOURCE_TYPE,
			SRCTC_DESCRIPTION		DESCRIPTION,
			SRCTC_ABBREVIATION		ABBREVIATION,
			SRCTC_STATUS			STATUS,
			SRCTC_MADE_BY			MADE_BY,
			SRCTC_MADE_ON			MADE_ON,
			SRCTC_UPDATED_BY		UPDATED_BY,
			SRCTC_LAST_UPDATE		LAST_UPDATE
	  FROM CTRLT_SOURCE_TYPE
     WHERE SRCTC_DESCRIPTION like v_description
	   AND ( v_status = BLANK OR v_status = SRCTC_STATUS )
	 ORDER BY SRCTC_DESCRIPTION;
END$$

DELIMITER ;