DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_CITY_LIST`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `CTRLPS_CITY_LIST`(
					IN p_id_country varchar(02) )
BEGIN
	SELECT	CTRYP_ID_COUNTRY 	ID_COUNTRY,
			CITYP_ID_CITY	 	ID_CITY,
			CITYC_CITY_NAME	 	CITY_NAME,
			CITYC_ABBREVIATION	ABBREVIATION
	  FROM CTRLT_CITY
     WHERE CTRYP_ID_COUNTRY = p_id_country;
END$$

DELIMITER ;