DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_ROOM`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `CTRLPS_ROOM`(
								IN p_id_hotel	varchar(02),
								IN p_id_room	varchar(04) )
BEGIN
	SELECT	ROOMP_ID_ROOM		ID_ROOM,
			MAINP_ID_HOTEL		ID_HOTEL,
			RTYPF_ID_ROOM_TYPE	ID_ROOM_TYPE,
			ROOMC_ROOM_NUMBER	ROOM_NUMBER,
			ROOMC_DESCRIPTION	DESCRIPTION,
			ROOMC_LOCATION		LOCATION,
			ROOMC_ROOM_RATE		ROOM_RATE,
			ROOMC_MAX_BEDS		MAX_BEDS,
			ROOMC_CONNECTION	ROOM_CONNECTION,
			RESVC_ID_RESERVATION ID_RESERVATION,
			ROOMC_HK_STATUS 	HK_STATUS,
			ROOMC_STATUS 		STATUS,
			ROOMC_MADE_BY		MADE_BY,
			ROOMC_MADE_ON		MADE_ON,
			ROOMC_UPDATED_BY	UPDATED_BY,
			ROOMC_LAST_UPDATE	LAST_UPDATE
	  FROM CTRLT_ROOM
	 WHERE p_id_hotel = MAINP_ID_HOTEL
	   AND p_id_room  = ROOMP_ID_ROOM;
END$$

DELIMITER ;