DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_CITY`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `CTRLPS_CITY`(
								IN p_id_country int,
								IN p_id_city int )
BEGIN
	SELECT	CTRYP_ID_COUNTRY	ID_COUNTRY,
			CITYP_ID_CITY		ID_CITY,
			CITYC_CITY_NAME		CITY_NAME,
			CITYC_ABBREVIATION	ABBREVIATION
	  FROM CTRLT_CITY
	 WHERE p_id_country = CTRYP_ID_COUNTRY
       AND p_id_city = CITYP_ID_CITY;
END$$

DELIMITER ;