DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_SEGMENT`$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `CTRLPS_SEGMENT`(
								IN p_id_hotel	varchar(02),
								IN p_id_segment	varchar(02) )
BEGIN
	SELECT	SEGMP_ID_SEGMENT	ID_SEGMENT,
			MAINP_ID_HOTEL		ID_HOTEL,
			SRCEF_ID_SOURCE		ID_SOURCE,
			SEGMC_DESCRIPTION	DESCRIPTION,
			SEGMC_MADE_BY		MADE_BY,
			SEGMC_MADE_ON		MADE_ON,
			SEGMC_UPDATED_BY	UPDATED_BY,
			SEGMC_LAST_UPDATE	LAST_UPDATE,
			SEGMC_STATUS 		STATUS
	  FROM CTRLT_SEGMENT
	 WHERE p_id_hotel = MAINP_ID_HOTEL
	   AND p_id_segment  = SEGMP_ID_SEGMENT;
END$$

DELIMITER ;