DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPD_SOURCE_TYPE`$$

CREATE DEFINER=`root`@`localhost`

PROCEDURE `CTRLPD_SOURCE_TYPE`(IN p_id_source_type int )

BEGIN
	DELETE FROM CTRLT_SOURCE_TYPE
	 WHERE p_id_source_type = SRCTP_ID_SOURCE_TYPE
       AND SRCTC_STATUS != '*';
END$$

DELIMITER ;