DELIMITER $$

DROP PROCEDURE IF EXISTS `hotel`.`CTRLPS_SOURCE_TYPE`$$

CREATE DEFINER=`root`@`localhost`

PROCEDURE `CTRLPS_SOURCE_TYPE`(IN p_id_source_type int,
							   IN p_status		   varchar(01) )
BEGIN
	SELECT	SRCTP_ID_SOURCE_TYPE	ID_SOURCE_TYPE,
			SRCTC_DESCRIPTION		DESCRIPTION,
			SRCTC_ABBREVIATION		ABBREVIATION,
			SRCTC_STATUS			STATUS,
			SRCTC_MADE_BY			MADE_BY,
			SRCTC_MADE_ON			MADE_ON,
			SRCTC_UPDATED_BY		UPDATED_BY,
			SRCTC_LAST_UPDATE		LAST_UPDATE
	  FROM CTRLT_SOURCE_TYPE
	 WHERE p_id_source_type = SRCTP_ID_SOURCE_TYPE
	   AND ( p_status = '' OR p_status = SRCTC_STATUS );
END$$

DELIMITER ;