<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="t" %>

	<c:set var="item" value="${ReservationForm.item}" />
	<table class="TableContainer" align="center" style="width: 38em">
		<thead align="center">
			<tr><td colspan="2"></td></tr>
		</thead>

		<tbody>
		<tr><td class="" align="center" colspan="2">
				<label for="reservation">Reservation #&nbsp;</label>
			    <input type="hidden" name="item.idHotel" id="idHotel"
					value="${hotel}">
				<input type="hidden" name="item.type" id="reservationType"
					value="I">
				<input type="text"
					name="item.idReservation" id="reservation"
					value="${item.idReservation}" onkeyup="decideEdit(event)"
					class="Small Number Remark" maxlength="6"
					title="Reservation code (autogenerated)"
					${ opexpected == 'i' ? 'readonly' : ''}>
				<label for="status" >
					<t:checkbox name="item.status" id="status" value="C"
						test="${item.status == 'C'}" />Confirmed
				</label>
			</td>
		</tr>
		<%--tr><td class="label">
				<label for="status">Status</label></td>
			<td><select name="item.status" id="status">
						<c:forEach var="item"
							items="${contextAttributes.reservationStatusList}">
							<c:if test="${ item.status eq item.status }">
								<c:set var="selected" value="SELECTED" />
							</c:if>
					<option value="${item.status}" ${selected}>
						${item.description}</option>
						</c:forEach>
				</select></td>
		</tr--%>

		<tr><td colspan="2">&nbsp;</td></tr>
		
		<c:set var="statusField" value="" />
		<c:if test="${opExpected == 'I'}"> <!-- Insert record -->
			<c:set var="statusField" value="DISABLED" />
		</c:if>

		<tr>
			<td class="Label">
				<label for="arrival">Arrival Date</label></td>
			<td class="">
				<label for="departure">Departure Date</label></td>
		</tr>

		<tr>
			<td colspan="2">
				<input type="text"
					name="item.departure" id="departure" value="${item.departure}"
					class="Small Remark Number" maxlength="10"
					title="Departure (DDMMYY)" onchange=""
					onkeyup="disableSaveButton(document.frmres)">
				<input type="text"
					name="item.arrival" id="arrival" value="${item.arrival}"
					class="Small Remark Number" maxlength="10"
					title="Arrival (DDMMYY)" onchange=""
					onkeyup="disableSaveButton(document.frmres)">
				<a href="javascript:searchItem()" title="Search Reservation">
					<img class="Tool" alt="Search reservations" src="images/lupa01.jpg">
				</a>
			</td>
		</tr>

		<tr>
			<td class="label" colspan="2">
				<label for="nights">Nights Stay</label></td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="text"
					name="item.nights" id="nights" value="${item.nights}"
					class="Tiny Remark Number" maxlength="3"
					title="Number of nights of guest stay"
					onchange="showTotal(this.form)"></td>
		</tr>
		<%--tr>
			<td class="label">
				<label for="flight">Arrival expected (Flight)</label></td>
			<td><input type="text" name="item.flight" id="flight" value="${item.flight}"
					class="Medium Remark" maxlength="20"
					title="Expected arrival time" onchange=""></td>
		</tr--%>
		<tr><td colspan="2">&nbsp;</td></tr>

		<tr>
			<td class="label" colspan="2">
				<label for="adults">Adults</label>&nbsp/&nbsp;
				<label for="adults">Children</label>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="text"
					name="item.adults" id="adults" value="${item.adults}"
					class="Tiny Number" maxlength="2"
					title="Adults in the room">
			    <input type="text"
					name="item.children" id="children" value="${item.children}"
					class="Tiny Number" maxlength="2"
					title="Children in the room">
			</td>
		</tr>

		<tr>
			<td class="label">
				<label for="roomType">Room Type</label></td>
			<td class="label">
				<label for="roomNumber">Room Number</label></td>
		</tr>
		<tr>
			<td><t:select name="item.roomType" id="roomType" value="${item.roomType}"
					items="${ReservationForm.roomTypeList}"
				/>
				<input type="button"
					onclick="javascript:showRoomTypeAvailability()"
					value="..." title="Muestra la disponibilidad por tipo para una
					fecha determinada" accesskey="" />
			</td>
			<td>
				<input type="text" name="item.roomNumber" id="roomNumber"
					value="${item.roomNumber}" items="${ReservationForm.roomNumberList}"
				>
				<input type="button"
					onclick="javascript:showRoomAvailability()"
					value="..." title="Muestra la disponibilidad de habitaciones para una
					fecha determinada" accesskey="" />
			</td>
		</tr>

		<tr>
			<td class="label">
				<label for="quantity">Quantity Rooms</label></td>
			<td class="label">
				<label for="quantity">Quantity Rooms</label></td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="text"
				name="item.quantity" id="quantity" value="${item.quantity}"
				class="Tiny Number" maxlength="3"
				title="Quantity of Rooms"></td>
		</tr>

		<tr><td colspan="2">&nbsp;</td></tr>

		<%--tr>
			<td class="label">
				<label for="package">Package</label></td>
			<td><select name="item.package" id="package" disabled="disabled">
					<option value="" selected>Package</option>
				</select></td>
		</tr--%>
		<tr>
			<td class="label" colspan="2">
				<label for="sourceCode">Source of bussiness</label></td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="hidden" name="item.idSource" id="idSource"
					value="${item.idSource}"/>
				<input type="text" id="sourceName"
					value="${item.sourceName}" readonly="readonly"
					style="width: 35em" />
				<input type="button"
					onclick="javascript:showSourceCodesList()"
					value="..." title="Muestra la disponibilidad de habitaciones para una
					fecha determinada" accesskey="" /></td>
		</tr>
		<tr>
			<td class="label">
				<label for="SpecialRate">Room Rate</label></td>
			<td class="label">
				<label for="balance">Total balance</label></td>
		</tr>
		<tr>
			<td>
				<input type="text"
					name="item.roomRate" id="roomRate" value="${item.roomRate}"
					class="Small Number" maxlength="10">
			</td>
			<td>
				<input type="hidden" name="item.total" id="total"
						value="${item.total}" />
				<input type="text" disabled="disabled"
					name="totalBalance" id="totalBalance" value="${item.total}"
					class="Small Number">
			</td>
		</tr>

		<!--tr><td colspan="2">&nbsp;</td></tr-->

		<!--tr>
			<td class="label">
				<label for="paymentDue">Payment Due</label></td>
			<td class="label">
				<label for="paymentType">Payment Type</label></td>
		</tr-->
		<!--tr>
			<td>
				<input type="text"
					name="item.paymentDue" id="paymentDue" value="${item.paymentDue}"
					class="Small Number" maxlength="10"
					title="Due Payment">
			</td>
			<td>
				<t:select name="item.paymentType" id="paymentType"
					value="${item.paymentType}" items="${ReservationForm.paymentTypeList}"/>
			</td>
		</tr-->

		<tr><td colspan="2"><br /></td></tr>
		</tbody>
	</table>
